name: graphql_ws
description: >-
  Coherent, zero-dependency, lazy, simple, GraphQL over WebSocket Protocol
  compliant client. Dart port of graphql-ws.
version: 0.1.0
repository: https://github.com/jungle-commerce/graphql-ws-dart
issue_tracker: https://github.com/jungle-commerce/graphql-ws-dart/issues

environment:
  sdk: ^3.5.0

resolution: workspace

dev_dependencies:
  graphql_ws_test_server:
    path: ../graphql_ws_test_server
  lints: ^6.1.0
  test: ^1.25.0
