name: _
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - packages/graphql_ws
  - packages/graphql_ws_flutter
  - packages/graphql_ws_test_server
  - packages/graphql_ws_web_socket_channel_connector
